<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class StudentsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Shandika Galih',
                'slug'          => 'shandika-galih',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Philip Miles',
                'slug'          => 'philip-miles',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Denni Halloway',
                'slug'          => 'denni-halloway',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Muhammad Andi',
                'slug'          => 'muhammad-andi',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Muhammad Shandi',
                'slug'          => 'muhammad-shandi',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Diana Caitilin',
                'slug'          => 'diana-caitilin',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Try Hansen',
                'slug'          => 'try-hansen',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Adam Sandler',
                'slug'          => 'adam-sandler',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Captain Marvel',
                'slug'          => 'captain-marvel',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Steve Roger',
                'slug'          => 'steve-roger',
                'db_kelasid'    => '1',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Steve Roger',
                'slug'          => 'steve-roger',
                'db_kelasid'    => '2',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Muhammad Fikran',
                'slug'          => 'muhammad-fikran',
                'db_kelasid'    => '2',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Muhammad Fikri',
                'slug'          => 'muhammad-fikri',
                'db_kelasid'    => '2',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Ai Hosino',
                'slug'          => 'ai-hosino',
                'db_kelasid'    => '2',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Aqua Hoshino',
                'slug'          => 'aqua-hosino',
                'db_kelasid'    => '2',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Ruby Hosino',
                'slug'          => 'ruby-hosino',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Kanna Hanazawa',
                'slug'          => 'kanna-hanazawa',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Tommy Blackburn',
                'slug'          => 'tommy-blackburn',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Jane Hayes',
                'slug'          => 'jane-hayes',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Robbie Kent',
                'slug'          => 'robbie-kent',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Andrea Craig',
                'slug'          => 'andrea-craig',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'michael-french',
                'slug'          => '',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Aida Gilbert',
                'slug'          => 'aida-gilbert',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Cecil Dickson',
                'slug'          => 'cecil-dickson',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Lydia Ayers',
                'slug'          => 'lydia-ayers',
                'db_kelasid'    => '3',
                'db_jurusanid'  => '1',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Claud Mcintosh',
                'slug'          => 'claud-mcintosh',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Candy Christian',
                'slug'          => 'candy-christian',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Teddy Sweeney',
                'slug'          => 'teddy-sweeney',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Miquel Wheeler',
                'slug'          => 'miquel-wheeler',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'August Beck',
                'slug'          => 'august-beck',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Rodger Potter',
                'slug'          => 'rodger-potter',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Bettie Wade',
                'slug'          => 'bettie-wade',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'George Lambert',
                'slug'          => 'george-lambert',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Emory Stanton',
                'slug'          => 'emory-stanton',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Sheila Branch',
                'slug'          => 'sheila-branch',
                'db_kelasid'    => '4',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Cassandra Harrington',
                'slug'          => 'cassandra-harrington',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Jerrod Parsons',
                'slug'          => 'jerrod-parsons',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Claudio Watkins',
                'slug'          => 'claudio-watkins',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Eddy Fuller',
                'slug'          => 'eddy-fuller',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Raphael Ross',
                'slug'          => 'raphael-ross',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Kristen Carroll',
                'slug'          => 'kristen-carroll',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Aimee Warner',
                'slug'          => 'aimee-warner',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Harlan Andrade',
                'slug'          => 'harlan-andrade',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'David Cobb',
                'slug'          => 'david-cobb',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            [
                'sampul'        => 'default.png',
                'studentname'   => 'Meagan Wells',
                'slug'          => 'meagan-wells',
                'db_kelasid'    => '5',
                'db_jurusanid'  => '2',
            ],
            ];
            $this->db->table('tb_students')->insertBatch($data);
    }
}
